name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: npm ci
      - run: npm test -- --browsers ChromeHeadlessNoSandbox --watch=false
      - run: npm run lint
